import type Ionicons from 'react-native-vector-icons/Ionicons';

/** Ionicons glyph names used across SaathiRide. */
export type AppIconName = React.ComponentProps<typeof Ionicons>['name'];

export const Icons = {
  add: 'add-circle-outline',
  back: 'chevron-back',
  bell: 'notifications-outline',
  calendar: 'calendar-outline',
  camera: 'camera-outline',
  car: 'car-outline',
  carSport: 'car-sport-outline',
  cash: 'cash-outline',
  check: 'checkmark',
  checkCircle: 'checkmark-circle-outline',
  chevronDown: 'chevron-down',
  close: 'close-circle-outline',
  closeCircle: 'close-circle',
  diamond: 'diamond-outline',
  document: 'document-text-outline',
  down: 'arrow-down',
  edit: 'pencil-outline',
  error: 'alert-circle-outline',
  flag: 'flag-outline',
  forward: 'arrow-forward',
  home: 'home-outline',
  hourglass: 'hourglass-outline',
  list: 'list-outline',
  location: 'location-outline',
  lock: 'lock-closed-outline',
  logOut: 'log-out-outline',
  mail: 'mail-outline',
  map: 'map-outline',
  megaphone: 'megaphone-outline',
  mountain: 'trail-sign',
  palette: 'color-palette',
  passenger: 'bag-outline',
  person: 'person-outline',
  phone: 'phone-portrait-outline',
  remove: 'remove',
  road: 'navigate-outline',
  search: 'search-outline',
  seat: 'people-outline',
  shield: 'shield-checkmark',
  star: 'star',
  starOutline: 'star-outline',
  swap: 'swap-vertical',
  sparkles: 'sparkles',
  ticket: 'ticket-outline',
  time: 'time-outline',
  trophy: 'trophy-outline',
  wallet: 'wallet-outline',
  warning: 'warning-outline',
  water: 'water-outline',
  city: 'business-outline',
  ban: 'ban-outline',
  bulb: 'bulb-outline',
} as const satisfies Record<string, AppIconName>;
